# Default values for pdns.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pdns:
  api:
    key: PowerDNSAPI
  recursor:
    webserver:
      allowFrom: 0.0.0.0/0
    config: |-
      daemon=no
      local-address=0.0.0.0
      local-port=53
      allow-from=0.0.0.0/0
      setgid=recursor
      setuid=recursor
      forward-zones-recurse=.=1.1.1.1;8.8.8.8
      webserver=yes
      webserver-port=8081
      webserver-address=0.0.0.0
      trace=yes

replicaCount: 1

image:
  repository: lmnetworks/pdns-recursor
  tag: 4.1.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - powerdns-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

##
## MariaDB chart configuration
##
mariadb:
  enabled: true

  db:
    name: powerdns
    user: powerdns
    password: powerdns

  replication:
    enabled: false

  master:
    persistence:
      enabled: false
      storageClass: "managed-nfs-storage"
      accessModes: [ReadWriteOnce]
      size: 2Gi
