apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pdns.fullname" . }}
  labels:
    app: {{ template "pdns.name" . }}
    chart: {{ template "pdns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Files.Get "recursor.conf" }}
