apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pdns-recursor-helm.fullname" . }}
  labels:
    app: {{ include "pdns-recursor-helm.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pdns-recursor-helm.fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ include "pdns-recursor-helm.fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      volumes:
        - name: config
          configMap:
            name: {{ include "pdns-recursor-helm.fullname" . }}
            items:
              - key: recursor.conf
                path: recursor.conf
        - name: zones
          configMap:
            name: {{ include "pdns-recursor-helm.fullname" . }}
            items:
              {{- range .Values.pdns.recursor.zones }}
              - key: {{ .name }}.conf
                path: {{ .name }}.conf
              - key: {{ .name }}.zone
                path: {{ .name }}.zone
              {{- end}}
        - name: api-data
          {{- if .Values.pdns.recursor.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pdns-recursor-helm.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      containers:
        - name: {{ include "pdns-recursor-helm.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/usr/sbin/pdns_recursor"]
          args: ["--api-key=$(PDNS_API_KEY)", "--webserver-allow-from={{ .Values.pdns.recursor.webserver.allowFrom }}"]
          env:
            - name: PDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "pdns-recursor-helm.fullname" . }}
                  key: api-key
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /etc/pdns
          - name: zones
            mountPath: /zones
          - name: api-data
            mountPath: /data
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
