apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      volumes:
        - name: config
          configMap:
            name: {{ template "fullname" . }}
      containers:
        - name: {{ template "fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          command: ["/usr/sbin/pdns_recursor"]
          args: ["--api-key=$(PDNS_API_KEY)", "--webserver-allow-from={{ .Values.pdns.recursor.webserver.allowFrom }}"]
          env:
            - name: MYSQL_HOST
              value: {{ template "mariadb.fullname" . }}
            - name: MYSQL_USER
              value: "root"
              value: {{ .Values.mariadb.db.user | quote }}
            - name: MYSQL_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ template "mariadb.fullname" . }}
                  key: mariadb-password
            - name: MYSQL_DB
              value: {{ .Values.mariadb.db.name | quote }}
            - name: PDNS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "fullname" . }}
                  key: api-key
          ports:
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: api
              containerPort: 8081
              protocol: TCP
          volumeMounts:
          - name: config
            mountPath: /etc/pdns/recursor.conf
            subPath: recursor.conf
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
